# hash:sha256:92c3e0355629b84dbfaf628a76a2a24289bdfec8c1b1423fb08cbeb20ecfa029
FROM registry.useast1.r2220.aws.codeocean.dev/codeocean/r-base:4.2.1-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /

ENV Camels=100
